tweag/jupyenv

generate-directory.sh
This also adds the missing nodejs package (npm is required).
=> generate-directory.sh uses nix-shell --pure

example/Haskell/bayesMonad/dice_example.ipynb, example/Haskell/bayesMonad/shell.nix
this example shows how to use a custom override on top of the default overrides using the monad-bayes library https://github.com/adscib/monad-bayes .
=> monad-bayes example

README.md
This updates the instructions for disabling the sandbox for the latest version of Nix.
=> Update sandbox instructions

nix/haskell-overlay.nix, nix/python-overlay.nix
This allows you to overlay the packages supplied by `jupyterWith` on top of your
own pkgs.
For example:
```nix
let
jupyterWithSrc = pkgs.fetchFromGitHub {
owner = "tweag";
repo = "jupyterWith";
rev = "...";
sha256 = "...";
};
pythonOverlay =
import "${jupyterWithSrc}/nix/python-overlay.nix";
jupyterPkgs =
pkgs.appendOverlays [ pythonOverlay ];
jupyterWith =
import jupyterWithSrc { pkgs = jupyterPkgs; };
```
Note that it's already possible to supply overlays to `jupyterWith`, but it's not the same as this. This is about overlaying jupyter on top of your own package sets rather than about overriding the packages supplied by `jupyterWith`.
(I personally think it would be more friendly if jupyterWith supplied overlays with these renamed to `ipythonPackages` and `ihaskellPackages`. But I …
=> Compose python/haskell overlays with any overlays that came before.

default.nix, example/Haskell/Frames/shell.nix, example/Haskell/Funflow/shell.nix, example/Haskell/dataHaskell/shell.nix, example/Haskell/diagrams/shell.nix, example/Haskell/tensorflow/shell.nix, nix/haskell-overlay.nix
This moves most of the overrides from the haskell overlay level to the
per project shell.nix level.
This will simplify the updating of Nixpkgs later.
=> Make most overrides local

README.md, nix/overlay.nix
This should allow using JupyterWith as an overlay. The interface is not
ideal, but this allows to using different Nixpkgs snapshots (as long
APIs do not change).
=> Add an overlay file for JupyterWith

default.nix, example/Python/local-package/shell.nix
This allows uses to add extra packages they may need to the JupyterWith
environment if needed. One popular request is Pandoc.
=> extraPackages parameter for default.nix

kernels/ihaskell/default.nix
This lets the libraries that are accessible for the Haskell kernel be
accessible from the terminal. In order to launch the Haskell interpreter,
just run ghci-$NAME, where NAME is the name of the kernel given in
the kernel configuration. The same works for ghc-$NAME.
The name given is different so that multiple Haskell kernels in the same
environment do not clash due to having the same name.
=> Haskell kernel libraries are accessible from interpreter

kernels/ipython/default.nix
This lets the libraries that are accessible for the Python kernel be
accessible from the terminal. In order to launch the Python interpreter,
just run `python-$NAME`, where NAME is the name of the kernel given in
the kernel configuration.
The name given is different so that multiple Python kernels in the same
environment do not clash due to having the same name.
=> Python kernel libraries are accessible from interpreter

README.md, default.nix
```
jupyterLabEnvironment = jupyter.jupyterlabWith {
extraJupyterPath = "${builtins.toPath ./.}/local_module/";
};
```
Adds another way to do local python modules, as the provided example allows for nix-wrapped python modules only - which does not allow for developing the module while the notebook is running. Let me know what you think about it, if you want docs, etc. Thanks.
=> [feature] adds a "extraJupyterPath" arguments for local python module development.

kernels/ipython/README.md, kernels/ipython/default.nix
In my opinion and python experience.  this argument should be here.
What do you think?
=> Is it necessary to set python's argument of ignore collisions  to true by default?

README.md, default.nix
This should allow the solution in #86 to be written as:
```nix
let
jupyter = import (builtins.fetchGit {
url = https://github.com/tweag/jupyterWith;
rev = "8a81a4aeffa339b80f23b88ca4de69423712c24a";
}) {};
iPython = jupyter.kernels.iPythonWith {
name = "notebook";
packages = p: with p; [
numpy
matplotlib
];
};
jupyterEnvironment =
jupyter.jupyterlabWith {
kernels = [ iPython ];
directory = ./jupyterlab;
extraPackages = p: [p.python3Packages.jupytext];
extraJupyterPath = p: "${p.python3Packages.jupytext}/lib/python3.7/site-packages";
};
in
jupyterEnvironment.env
```
Take a look @mdtisdall.
=> Make the extraJupyterPath parameter a function

README.md
This generator is the cause of most issues registered in JupyterWith,
and is merely a convenience, with any more sofisticated use-case needing
a manually generated folder.
Therefore, I think it is not worth its weight, and it is better to
remove it.
@MMesch Just checking if you think this is a good idea too.
=> Large warning for impure generator

README.md, default.nix, example/Haskell/Funflow/shell.nix, example/Haskell/diagrams/shell.nix, example/Haskell/ihaskell_labextension.nix, lib/directory.nix
Add a `mkBuildExtension` function which creates a JupyterLab extension derivation from an extension source directory. This allows us to build __ihaskell_labextension__ from the Github repo instead of from NPM.
This Haskell examples *Funflow* and *diagrams* now produce a JupyterLab 2 with a working __ihaskell_labextension__. (All the other Haskell examples are currently not buildable at all?)
What do you think about this @guaraqe  ? Something like this would resolve #111 and also https://github.com/gibiansky/IHaskell/issues/1159 .
=> Build ihaskell_labextension from Github, not NPM

README.md, nix/haskell-overlay.nix
Basic Haskell syntax highlighting in jupyterlab can now be obtained with a simple command line flag.
=> Bump ihaskell. No need for jupyterlab-ihaskell anymore

.github/workflows/nix-linux.yml, .github/workflows/nix-macos.yml, kernels/ihaskell/default.nix, tests/custom-ihaskell.nix, tests/default.nix, tests/test-kernel-path.nix
When attempting to integrate a haskell.nix project with IHaskell and jupyterWith, I ran into an issue where the `ghcWithPackages` function in the [haskell.nix](https://github.com/input-output-hk/haskell.nix) haskell package set doesn't add executables to the ghc environment it creates. This causes jupyterWith to generate an invalid ihaskell kernel file since the path it contains points to a non-existent ihaskell executable.
This PR addresses this issue by adding an extra input to the ihaskell kernel derivation which allows users to optionally specify a custom ihaskell derivation instead of using the one that resides in the input haskellPackages set. This allows users of haskell.nix to use the packages they build using that with jupyterWith + ihaskell. The default ihaskell is still the …
=> Add option for custom ihaskell path

default.nix
Use case: using nixpkgs from jupyterWith to add custom packages (e.g.
manually or with mach-nix) for use in the final environment.
=> default.nix: export nixpkgs

lib/directory.nix
This PR related my comment at https://github.com/tweag/jupyterWith/issues/124#issuecomment-694153591
- test with python38(recent nixpkgs)
```
wrapping `/nix/store/s1j7fk9sm91q4jzdv1747yrfqla31v51-python3.8-jupyterlab-2.2.4/bin/jupyter-lab'...
Rewriting #!/nix/store/685kq8pyhrvajah1hdsfn4q7gm3j4yd4-python3-3.8.5/bin/python3.8 to #!/nix/store/685kq8pyhrvajah1hdsfn4q7gm3j4yd4-python3-3.8.5
wrapping `/nix/store/s1j7fk9sm91q4jzdv1747yrfqla31v51-python3.8-jupyterlab-2.2.4/bin/jupyter-labextension'...
Rewriting #!/nix/store/685kq8pyhrvajah1hdsfn4q7gm3j4yd4-python3-3.8.5/bin/python3.8 to #!/nix/store/685kq8pyhrvajah1hdsfn4q7gm3j4yd4-python3-3.8.5
wrapping `/nix/store/s1j7fk9sm91q4jzdv1747yrfqla31v51-python3.8-jupyterlab-2.2.4/bin/jupyter-labhub'...
Executing pythonRemoveTestsDir
Finished …
```
=>  lib.mkDirectory: replace python3.7 to sitePackages

default.nix
`jupyterlabWith` is defined as a modified `python3.jupyterlab`, but it
also retains a reference to original by capturing it with
`defaultDirectory`. Since a modified version will have the same
directory, we can use `$out/share/jupyter/lab` instead.
=> Don't duplicate jupyterlab package in jupyterlabWith

kernels/iruby/gemdir/Gemfile, kernels/iruby/gemdir/Gemfile.lock, kernels/iruby/gemdir/gemset.nix, kernels/iruby/gemdir/generate.sh, tests/default.nix
This fixes the ruby kernel by updating `iruby` to 0.7.4, and removing unnecessary gems.
=> Fix ruby kernel

.github/workflows/nix-macos.yml, default.nix, example/flake/flake.lock, nix/python-overlay.nix, tests/default.nix
This disables the default python kernel in `jupyter-lab`, `jupyter-notebook`, and `jupyter-nbclassic`.
=> Disable default python kernel

default.nix
There are two changes:
1. Wrap jupyterlab so that `extraPackages` are added to its PATH, not only to the dev shell. I was looking for a way to do this (e.g. to add texlive so that I can export to PDF), found `extraPackages` and was really surprised that it did not do what I expected.
2. Add NodeJS to PATH (fixes #189).
=> Allow PATH customisation and add NodeJS to PATH

nix/python-overlay.nix
This should fix #188 
The overlays were modified to only wrap `jupyter-lab`, `jupyter-notebook` and `jupyter-nbclassic` binaries. And it leaves untouched the other binaries that the derivations produce (in particular, `jupyter-labextension` for the issue mentioned above).
@kirelagin, Can you please check that this works as intended?
=> Wrap only necessary jupyter binaries

default.nix
`pkgs.python3Packages` doesn't work with `flake.nix`
=> fix pkgs.python3Packages to pkgs.python3.pkgs for flake

flake.nix
JupyterLab expected certain directories, for user settings and workspaces, to exist under Jupyter's config directories. The needed directories were adding to the `jupyterDir` derivation so we can add config files in the future.
=> next-feature/fix-jupyter-paths

flake.nix
Closes #226.
JupyterLab user settings and workspaces directories have been updated with a temporary fix.
While debugging, it was discovered that the Jupyter data directory also needed to be moved to a writable location. It also has been given a temporary fix.
=> Next feature/fix jupyter lab paths

flake.nix
Fixes #230. `IPYTHONDIR` should be set to a writable location similar to what was down for the jupyterlab user settings and workspaces directories in #229.
=> Set IPYTHONDIR to a temporary controlled location.

default.nix, nix/python-overlay.nix
1. Allow users to override `python3` in `default.nix` so that one can either change the version of `python3` or override `python3` with custom python environment such as `poetry2nix` python environment.
2. When using `jupyterWith` with `poetry2nix`, duplicated packages error occur often a lot due to each of them making separate set of python packages. To overcome the problem, `poetry2nix` needs to be able to override `jupyterWith` overlay in its `defaultPoetryOverrides`.
=> Move `python3` to overridable scope. Allow `poetry2nix` to override `nix/python-overlay.nix`

kernels/bash/default.nix
Bash kernel needs to use bash interactive.
=> Use bashInteractive instead of bash.

flake.nix, template/README.md, template/default.nix, template/flake.nix, template/kernels/ihaskell.nix, template/kernels/ipython.nix, template/shell.nix
Updates the template flake, default, and shell files.
Removes the haskell kernel for now. Focusing on the python kernel.
To test, change the flake inputs url for jupyterWith to pull from `main` until it becomes the default branch.
=> next-feature/update-templates

flake.nix
Makes Julia available after running `nix build .#jupyterlab-all-kernels` or `nix build .#jupyterlab-kernel-julia`. Will not add Julia to the build if the IJulia kernel is not present. Useful for CI.
=> Added julia to wrapped jupyterlab env if julia kernel is present.

flake.nix, template/README.md, template/kernels/python.nix
- Modifed `getKernelInstance` so it returns `kernelName` instead of `name`. We use `name` in the available kernels and we do not want to confuse users who might pass `name` without realizing the `name` attribute of a kernel instance must be unique.
- Updated the template kernel to use `kernelName` as well.
- Updated the template kernel to use override. This was missed by me in a previous PR.
- Updated the template readme to use the new terminology: available kernels, kernel instance, and kernel derivation.
@garbas we have two names that we should resolve:
`mkJupyterInstance`
`mkJupyterEnvironmentFromPath`
We should pick either instance or environment and use it for both. I vote for environment so as not to mix it up with kernel instance, but could be convinced otherwise. Thoughts?
=> Next feature/update docs and code

flake.nix, template/README.md
Fixed `nix flake check` failing in CI because `mdformat` was not found.
Having `jupyterlab` available in the devShell allows `pre-commit run -a` to work locally but not in CI. Fixed by updating the `pre-commit` hooks.
=> Next feature/fix mdformat ci

kernels/available/bash/overrides.nix, kernels/available/bash/poetry.lock, kernels/available/bash/pyproject.toml
Fixes #298. Fixes #232.
In addition to no longer having to patch the bash kernel's `pyproject.toml` file, the latest version appears to have fixed an issue where every cell raised an exception: https://github.com/takluyver/bash_kernel/issues/121.
Broken CI is fixed in https://github.com/tweag/jupyterWith/pull/305.
=> Update bash kernel to 0.8.0.

flake.lock, flake.nix, kernels/available/typescript/default.nix, kernels/example/python/science/default.nix, kernels/example/python/science/test.ipynb, kernels/example/python/science/test.py
Updates the top level flake inputs.
Addes a new python kernel example with `numpy`, `scipy`, and `matplotlib` to check that those packages work with the `extraPackages` argument.
Use new npmlock2nix v2 API.
Use new pre-commit API.
=> Update flake lock and add new CI tests

kernels/available/haskell/default.nix
I can only get Codemirror working if I add the `--codemirror Haskell` kernel commandline arg.
Resolves #438
=> IHaskell Codemirror syntax highlighting enable

docs/documentation/how-to.md
Poetry does not lock down information about the build system used to build dependencies. As such poetry2nix cannot automatically figure out build inputs. https://github.com/nix-community/poetry2nix/issues/568
This documents how to help poetry2nix out with figuring out build inputs such as the issue in  #442
=> Document ModuleNotFoundError
