- .gitignore
- default.nix
- example/cities-wordcloud/kernelWith.nix
- generate-directory.sh
- nix/nixpkgs.nix
A few improvements to mostly the nix code.
> Nix improvements

- example/Haskell/bayesMonad/dice_example.ipynb
beginning of logistic regression example
> updated Monad Bayes example

- example/Haskell/local-package/my-haskell-package/MyHaskellPackage.hs
- example/Haskell/local-package/my-haskell-package/default.nix
- example/Haskell/local-package/my-haskell-package/haskell-src.cabal
- example/Haskell/local-package/shell.nix
> add an example that calls a local package

- example/Python/local-package/my-python-package/mypackage/__init__.py
- example/Python/local-package/my-python-package/setup.py
- example/Python/local-package/shell.nix
> Add a python example with a local package

- default.nix
- example/Python/local-package/shell.nix
> change location of extraPackages parameter

- example/Python/poetry2nix/README.md
- example/Python/poetry2nix/poetry.lock
- example/Python/poetry2nix/pyproject.toml
- example/Python/poetry2nix/shell.nix
The goal of this PR is to set up an example using `poetry2nix` to specify the exact versions of the packages.
> An example with poetry2nix

- README.md
As proposed in https://github.com/tweag/jupyterWith/issues/86.
> Improve README for Python overrides

- README.md
- nix/overlay.nix
- tests/test-overlay.nix
> Fix overlay problems

- README.md
Should solve the first part of #102.
> More documentation for generate-directory

- .github/workflows/nix-flake.yaml
- example/flake/devshell.nix
- example/flake/flake.lock
- example/flake/flake.nix
- flake.lock
- flake.nix
- CI
```
nix develop ./example/flake --command echo OK
```
> add flake support

- .github/workflows/nix-flake.yaml
- example/flake/flake.lock
- example/flake/flake.nix
- flake.lock
- flake.nix
- nix/haskell-overlay.nix
- nix/nixpkgs.nix
- nix/python-overlay.nix
I'm going to fix the PR of https://github.com/tweag/jupyterWith/pull/173 problem.
> Fix darwin build and bumup nixpkgs

- .github/workflows/nix-flake.yaml
- example/flake/flake.lock
- example/flake/flake.nix
- flake.lock
- flake.nix
- nix/haskell-overlay.nix
- nix/nixpkgs.nix
I've added a flake to ihaskell recently. We can fetch the ihaskell overlay from that flake to avoid code duplication.
> Use ihaskell flake

- README.md
I added a simple flake example directly to the README. We should probably also add how this can be initialized directly with `nix flake init -t`.
> Flake example in README

- .github/dependabot.yml
- .github/workflows/update-flake-lock.yml
* add dependabot to update github actions
* add update-flake-lock github workflow to update flake.lock file
> Improve CI

- flake.nix
> Next bugfix/fix ipythondir again

- kernels/c/overrides.nix
- kernels/c/poetry.lock
- kernels/c/pyproject.toml
> Next feature/fix c kernel

- README.md
Signed-off-by: Dylan Madisetti <dylan.madisetti@gmail.com>
> Syntax fix for README

- README.md
Signed-off-by: Carl Thomé <carlthome@gmail.com>
> jupter -> jupyter

- .github/settings.yaml
- LICENSE
Added github settings for labels.
Update the Tweag License.
> Updated github settings and repo license.

- flake.nix
- template/README.md
- template/kernels/python.nix
Updated template welcome text.
Fixed template python kernel name.
Added instructions in the template readme for extending existing kernels and creating custom kernels.
> Next feature/update documenation

- README.md
PR #285 modified the path, but forgot to update the readme
> Fix logo path

- flake.lock
- flake.nix
- kernels/available/julia/README.md
- kernels/available/julia/default.nix
- kernels/available/julia/shell.nix
Fixes #296.
nixpkgs has updated Julia to 1.8 and deprecated 1.7. See https://github.com/NixOS/nixpkgs/pull/189656
> updated julia to use latest 1.8.1 version.

- nix/default.nix
Fixes #286 
Signed-off-by: Rok Garbas <rok@garbas.si>
> config was never used with nixpkgs

- flake.nix
> Extended jupyter lab env to take all arguments provided by poetry2nix.

- .github/workflows/ci.yml
> Run python kernel test with template

- config.nix
- flake.nix
- kernels/available/bash/default.nix
- kernels/available/bash/module.nix
- kernels/available/haskell/module.nix
- kernels/available/javascript/module.nix
- kernels/available/julia/module.nix
- kernels/example/bash/minimal/default.nix
- kernels/example/c/minimal/default.nix
- kernels/example/elm/minimal/default.nix
- kernels/example/go/minimal/default.nix
- kernels/example/haskell/minimal/default.nix
- kernels/example/javascript/minimal/default.nix
- kernels/example/julia/minimal/default.nix
- kernels/example/nix/minimal/default.nix
- kernels/example/ocaml/minimal/default.nix
- kernels/example/postgres/minimal/default.nix
- kernels/example/python/minimal/default.nix
- kernels/example/python/stable/default.nix
- kernels/example/r/minimal/default.nix
- kernels/example/rust/minimal/default.nix
- kernels/example/scala/minimal/default.nix
- kernels/example/typescript/minimal/default.nix
- kernels/example/zsh/minimal/default.nix
- modules/default.nix
Updates the example in the main flake file.
Also makes some fixes to some kernel module.nix files.
> New UI (Update Examples)

- docs/blogs/release-0.1.0.md
- docs/community/get-involved.md
- mkdocs.yml
Addes a Community tab to the site.
Updates matrix links to point to the new space.
> New UI (Community tab and Matrix links)

- kernels/available/julia/default.nix
IJulia has updated to 1.24.0 and the path in the depot has changed.
> updated ijulia version slug.

- jupyterlab.nix
- kernels/available/python/default.nix
This PR from https://github.com/tweag/jupyterWith/pull/88, is also necessary for the current branch. yes, It has a little bit risky, if you want to use the nixpkgs.pythn3Pckages in the poetry env.
> Python: add ignoreCollisions argument 

- flake.nix
> Only evaluate julia lazily in flake.nix

- lib/jupyter.nix
> Fix the looping "needs to build JupyterLab" bug #421

- modules/kernels/ocaml/default.nix
Expand documentation for the ocaml kernel, linking to upstream opam-nix where necessary.
> Expand documentation for the ocaml kernel
